URL_SERVICE = 'https://cnt-f317e48e-8885-4f0b-9d69-9369e20295a7.containerhub.tripleten-services.com'
DOC_PATH = '/docs/'
LOG_MAIN_PATH = '/api/logs/main/'
USERS_TABLE_PATH = '/api/db/resources/user_model.csv'
CREATE_USER_PATH = '/api/v1/users/'
PRODUCT_KITS_PATH = '/api/v1/products/kits/'